source 'https://rubygems.org'
ruby '~> 3.1.0'

gem 'sinatra', '~> 2.2'
gem 'twilio-ruby', '~> 5.0'
gem 'json', '~> 2.6'
gem 'sinatra-websocket', '~> 0.3'
gem 'eventmachine', '~> 1.2'
gem 'puma', '~> 5.0'
gem 'rack', '~> 2.2'
